org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8 -Djdk.tls.client.protocols=TLSv1.2 --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED

systemProp.jdk.tls.client.protocols=TLSv1.2
systemProp.https.protocols=TLSv1.2
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Kotlin
kotlin.compiler.daemon.enabled=true
kotlin.incremental=true
kotlin.compiler.execution.strategy=in-process

# Workers (explicit, not empty)
org.gradle.workers.max=1

# Android
android.useAndroidX=true
android.enableJetifier=true

# Pin an NDK version that supports 16KB pages (r26b+)
android.ndkVersion=26.3.11579264

# Optional: silence AGP warning for compileSdk=36
android.suppressUnsupportedCompileSdk=36

# JDK 17
org.gradle.java.home=C\:\\Program Files\\Java\\jdk-17
