CREATE TABLE IF NOT EXISTS `PREFIX_product_enriched` (
    `id_product` INT(10) UNSIGNED NOT NULL,
    `id_product_attribute` INT(10) UNSIGNED NOT NULL DEFAULT 0,
    `id_shop` INT(10) UNSIGNED NOT NULL DEFAULT 1,
    `quantity` INT(10) NOT NULL DEFAULT 0,
    `price_ht` DECIMAL(20,6) NOT NULL DEFAULT 0.000000,
    `price_ttc` DECIMAL(20,6) NOT NULL DEFAULT 0.000000,
    `tax_rate` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    `id_tax_rules_group` INT(10) UNSIGNED NOT NULL DEFAULT 0,
    `has_discount` TINYINT(1) NOT NULL DEFAULT 0,
    `discount_type` VARCHAR(20) DEFAULT NULL COMMENT 'percentage or amount',
    `discount_value` DECIMAL(20,6) NOT NULL DEFAULT 0.000000,
    `discount_from` DATETIME DEFAULT NULL,
    `discount_to` DATETIME DEFAULT NULL,
    `final_price_ttc` DECIMAL(20,6) NOT NULL DEFAULT 0.000000,
    `is_active` TINYINT(1) NOT NULL DEFAULT 1,
    `reference` VARCHAR(64) DEFAULT NULL,
    `ean13` VARCHAR(13) DEFAULT NULL,
    `id_manufacturer` INT(10) UNSIGNED NOT NULL DEFAULT 0,
    `manufacturer_name` VARCHAR(128) DEFAULT NULL,
    `updated_at` DATETIME NOT NULL,
    `synced_at` DATETIME DEFAULT NULL,
    PRIMARY KEY (`id_product`, `id_product_attribute`, `id_shop`),
    INDEX `idx_active` (`is_active`),
    INDEX `idx_updated` (`updated_at`),
    INDEX `idx_reference` (`reference`),
    INDEX `idx_ean13` (`ean13`),
    INDEX `idx_manufacturer` (`id_manufacturer`),
    INDEX `idx_quantity` (`quantity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
